# SConscript sledzeniekalmana/src/generator_app
# Author: Jan Kumor

Import('env', 'module')

import os

sources = Glob('*.cpp', strings=True)
print 'Source files in module: ' + module
print sources

result = env.Program('generator_app', sources)

Return('result')
