# SConscript sledzeniekalmana/src/filter_app
# Author: Jan Kumor

Import('env', 'module')

import os

sources = Glob('*.cpp', strings=True)
print 'Source files in module: ' + module
print sources

result = env.Program('filter_app', sources)

Return('result')