# SConscript sledzeniekalmana/src
# Author: Jan Kumor

Import('env', 'modules')

import os

for module in modules:
	mod = env.SConscript(module + os.sep + 'SConscript', exports=['env', 'module'], duplicate=0)
	
Return('mod')
