# SConscript sledzeniekalmana/src
# Author: Jan Kumor

Import('env', 'modules')

import os

for module in modules:
	env.SConscript(module + os.sep + 'SConscript', exports=['env', 'module'], duplicate=0)