# SConscript sledzeniekalmana/src
# Author: Jan Kumor

Import('env', 'modules')

import os

result = []

for module in modules:	
	result.append(env.SConscript(module + os.sep + 'SConscript', exports=['env', 'module'], duplicate=0))
	
print 'Targets: '
print result
Return('result')
