# SConscript sledzeniekalmana/src/network
# Author: Adam Moscicki

Import('env', 'module')

import os

sources = Glob('*.cpp', strings=True)
print 'Source files in module: ' + module
print sources

result = env.Library('network', sources)

Return('result')