# SConscript sledzeniekalmana/src/network
# Author: Adam Moscicki

Import('env_lib', 'module')

import os

sources = Glob('*.cpp', strings=True)
print 'Source files in module: ' + module
print sources

env_lib.Library('network', sources)
